### PR TITLE
Updates for 1.8.7 (need tested)

### PR DESCRIPTION
**Pull request by wriley**
I no longer have a DayZ mod server so these are UNTESTED CHANGES

### CODE REVIEW

**Comment by wriley** [comment]
@R4Z0R49 Needs tested before merge, I no longer have a server

**Comment by Grompel** [comment]
^Hey, i would like to test it! How can I download the release?

**Comment by wriley** [comment]
@Grompel You can checkout my branch via git

`git checkout -b wriley-updates_for_1.8.7 master
git pull git://github.com/wriley/DayZAdmin.git updates_for_1.8.7`

If that doesn't make sense to you let me know and I'll work out a way to get a zipfile to you.

**Comment by wriley** [comment]
Grompel reports that vehicles are missing from the map view. There are possibly other issues so I will work on getting a test server up and some data into it. No guarantee on timeline, real life has kept me pretty busy.

**Comment by wriley** [comment]
This branch appears to work fine on a test instance I setup. I'll see if I can get the map issue worked out for Grompel.

**Pull request merged**
